DROP TABLE IRRIGACOES;

DROP TABLE LEITURAS_SENSORES;

DROP TABLE FATORES_IRRIGACAO;

DROP TABLE AREAS CASCADE CONSTRAINTS;

DROP TABLE SENSORES CASCADE CONSTRAINTS;

-- Cria as tabelas do banco de dados
CREATE TABLE AREAS (
    ID_AREA NUMBER PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    HECTARES NUMBER NOT NULL,
    CULTURA VARCHAR2(50) NOT NULL
);

CREATE TABLE IRRIGACOES (
    ID_IRRIGACAO NUMBER PRIMARY KEY,
    ID_AREA NUMBER REFERENCES AREAS(ID_AREA),
    DT_INICIO TIMESTAMP NOT NULL,
    DT_FIM TIMESTAMP NOT NULL,
    QTD_AGUA NUMBER NOT NULL
);

CREATE TABLE SENSORES (
    ID_SENSOR NUMBER PRIMARY KEY,
    NOME_SENSOR VARCHAR2(50) NOT NULL
);

CREATE TABLE LEITURAS_SENSORES (
    ID_LEITURA NUMBER PRIMARY KEY,
    ID_AREA NUMBER REFERENCES AREAS(ID_AREA),
    ID_SENSOR NUMBER REFERENCES SENSORES(ID_SENSOR),
    DT_LEITURA TIMESTAMP NOT NULL,
    TIPO_VALOR VARCHAR(50) NOT NULL,
    VALOR NUMBER NOT NULL,
    UNIQUE(ID_AREA, ID_SENSOR, DT_LEITURA)
);

CREATE TABLE FATORES_IRRIGACAO (
    CULTURA VARCHAR2(50) PRIMARY KEY,
    FATOR NUMBER NOT NULL
);

-- Adiciona dados padrão para SENSORES

INSERT INTO SENSORES (ID_SENSOR, NOME_SENSOR) VALUES (1, 'Umidade do Solo');
INSERT INTO SENSORES (ID_SENSOR, NOME_SENSOR) VALUES (2, 'Alcalinidade do Solo');
INSERT INTO SENSORES (ID_SENSOR, NOME_SENSOR) VALUES (3, 'Nutrientes do Solo (NPK)');

-- Adiciona dados padrão para FATORES_IRRIGACAO
INSERT INTO FATORES_IRRIGACAO (CULTURA, FATOR) VALUES ('Milho', 0.8);
INSERT INTO FATORES_IRRIGACAO (CULTURA, FATOR) VALUES ('Soja', 0.7);
INSERT INTO FATORES_IRRIGACAO (CULTURA, FATOR) VALUES ('Café', 0.6);